<p class="title-menu"><span class="alegreto-font">М</span><span class="title-menu-type">еню</span></p>
<ul class="right-menu">
    <?php foreach($this->container as $this->pages){?>
        <li class="right-menu-main">
            <span  <?php if($this->pages->isActive())echo 'class = "active"'; if(!$this->pages->visible) echo 'style="display:none;';?>>
                <a href="<?php echo  $this->pages->uri ?>" ><?php echo $this->pages->label  ?></a>
            </span>
        <?php foreach ($this->pages->pages  as $this->pages){  ;?>
            <ul   class="right-menu-sub" <?php  if(!$this->pages->visible) echo 'style="display:none;';?> >
               <li ><a href="<?php echo  $this->pages->uri ?>"  <?php if($this->pages->isActive())echo 'class = "right-menu-sub-active"';?> ><b><?php echo $this->pages->label  ?></b></a></li>
            </ul>
        <?php } ?>
        </li>
    <?php } ?>
</ul>

<!--<ul>-->
<!--    <li class="right-menu-main"><span class="active">Пункт 1</span>-->
<!--        <ul class="right-menu-sub">-->
<!--            <li>Подпункт 1.1</li>-->
<!--            <li>Подпункт 1.2  </li>-->
<!--        </ul>-->
<!--    </li>-->
<!--    <li class="right-menu-main"><span>Пункт 1</span>-->
<!--        <ul class="right-menu-sub">-->
<!--            <li>Подпункт 1.1</li>-->
<!--            <li>Подпункт 1.2  </li>-->
<!--        </ul>-->
<!--    </li>-->
<!--</ul>-->