<?php echo $this->doctype();?>
<?php //  echo $page->activePage['top']; exit;  ?>
<meta charset="utf-8">
<html lang="en">
    <head>

        <?php echo $this->headTitle('royal')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php
            echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
            echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                      ->prependStylesheet($this->basePath() . '/css/main.css')
                      ->prependStylesheet($this->basePath() . '/css/animate.css');
        ?>
        <!-- Scripts -->
        <?php
            echo $this->headScript()
            ->prependFile($this->basePath() . '/js/jquery.slides.min.js',   'text/javascript')
            ->prependFile($this->basePath() . '/js/jquery.textillate.js',   'text/javascript')
            ->prependFile($this->basePath() . '/js/jquery.fittext.js',   'text/javascript')
            ->prependFile($this->basePath() . '/js/jquery.lettering.js',   'text/javascript')
            ->prependFile($this->basePath() . '/js/jquery.min.js','text/javascript');
        ?>
<!--        <script type="text/javascript">-->
<!--            var message="";-->
<!--            function clickIE() {if (document.all) {(message);return false;}}-->
<!--            function clickNS(e) {if-->
<!--                (document.layers||(document.getElementById&&!document.all)) {-->
<!--                if (e.which==2) {-->
<!--                    (message);-->
<!--                    return false;}}}-->
<!--            if (document.layers) {-->
<!--                document.captureEvents(Event.MOUSEDOWN);-->
<!--                document.onmousedown=clickNS;-->
<!--            }else{-->
<!--                document.onmouseup=clickNS;-->
<!--                document.oncontextmenu=clickIE;-->
<!--            }-->
<!--            document.oncontextmenu=new Function("return false")-->
<!--        </script>-->
    </head>
        <body>
             <div class='wrapper'>
                <nav>
                    <header>
                        <img class="logo" src='/image/logo.png'>
                        <div class='header-menu-top'>
                            <?php
                                if(isset($page->activePage['top'])){

                                    $this->navigation($this->GetNavigationHelper('top'))->findOneByResource($page->activePage['top'])->setActive(true);
                                }else{
                                    $this->navigation($this->GetNavigationHelper('top'));
                                }
                                echo $this->navigation()->menu()->setPartial('template/navigation_top')->render();
                            ?>
                        </div>
                        <div class="border-slyder">
                            <div class="wrapper-slider">
                                <div class="container-slider">
                                        <div id="slides">
                                        <img src="/siteDir/slider/royal.png" />
                                        <img src="/siteDir/slider/slider.jpg" />
                                        <img src="/siteDir/slider/db_110532.jpg" />
                                        <img src="/siteDir/slider/db_135157.jpg" />
                                        <img src="/siteDir/slider/db_162282.jpg" />
                                        <img src="/siteDir/slider/db_164431.jpg" />
                                    </div>
                                    <span class="desk-slider">Окружая Себя Прекрасным...</span>
                                </div>

                            </div>
                        </div>
                        <div class="menu-content ">
                            <div class='header-menu-bottom'>
                                    <?php
                                        if(isset($page->activePage['bottom'])){
                                            $this->navigation($this->GetNavigationHelper('bottom'))->findOneByResource($page->activePage['bottom'])->setActive(true);
                                        }else{
                                            $this->navigation($this->GetNavigationHelper('bottom'));
                                        }
    //                                    echo $this->navigation()->menu()->setPartial('template/navigation_top')->render();
    //                                        $this->navigation($this->GetNavigationHelper())->findOneByResource(1)->setActive($page->bootomActive);
                                        echo $this->navigation()->menu()->setPartial('template/navigation_bottom')->render();
                                    ?>
                            </div>
                        </div>
                    </header>
                </nav>
                 <div class="papirus">
                     <div class="warpper-uzor-top"><div class="uzor-top"></div></div>
                     <div class="content">
                         <div class="warpper-content">
                    <?php echo $this->content; ?>
             </div>
             <div class="uzor-down"></div>
             </div>
                 <div class="footer"></div>
                 <!-- /container -->
              <?php echo $this->inlineScript()
                  ->prependFile($this->basePath() . '/js/init.slides.js','text/javascript')
                  ->prependFile($this->basePath() . '/js/resize.border.slider.js','text/javascript');

              ?>


        </body>
</html>
