<?php echo $this->doctype();?>
<?php //  echo 123; exit;  ?>
<meta charset="utf-8">
<html lang="en">
    <head>
        <?php
            echo $this->headTitle('royal')->setSeparator(' - ')->setAutoEscape(false)
        ?>
        <?php
            echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?php
            echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                      ->prependStylesheet($this->basePath() . '/css/admin.css');
        ?>
        <!-- Scripts -->
        <?php
            echo $this->headScript()
                ->prependFile($this->basePath() . '/js/jquery.uploadify.js','text/javascript')
                ->prependFile($this->basePath() . '/js/jquery.fileupload.js','text/javascript')
                ->prependFile($this->basePath() . '/js/jquery.slides.min.js',   'text/javascript')
                ->prependFile($this->basePath() . '/js/jquery-ui.js','text/javascript')
                ->prependFile($this->basePath() . '/js/jquery.min.js','text/javascript');
//        var_dump($page->activePage['admin']['tab']);
//        exit;
        ?>
    </head>
        <body>
             <div class='wrapper'>
                <nav>
                    <header>
                        <img class="logo" src='/image/logo.png'>
                        <div class="menu-content ">
                            <div class='header-menu-bottom-admin'>
                                    <?php
                                        $this->navigation($this->GetNavigationHelper('admin'))
                                            ->findOneByResource($page->activePage['admin']['tab'])->setActive(true)
                                            ->findOneByResource($page->activePage['admin']['sub'])->setActive(true);
                                        echo $this->navigation()->menu()->setPartial('template/navigation_admin')->render();
                                    ?>
                            </div>
                        </div>
                    </header>
                </nav>
                 <div class="papirus">
                     <div class="content">
                         <div class="warpper-content">
                             <?php if($page->tab){  ?>

                                <?php foreach ($page->tab as $key) { ?>

                                     <div class="tab <?php
                                     if(isset($key['active']) && $key['active']===true ) echo 'active-tab'; ?>" >
                                         <a href="<?php echo $key['link'] ?>">
                                             <?php echo $key['title'] ?>
                                         </a>
                                     </div>

                                 <?php } ?>

                            <?php } ?>
                            <?php echo $this->content; ?>
                        </div>
                    </div>
                 <div class="footer"></div>
                 <!-- /container -->
<!--              --><?php //echo $this->inlineScript()
//                  ->prependFile($this->basePath() . '/js/init.slides.js','text/javascript')
//                  ->prependFile($this->basePath() . '/js/resize.border.slider.js','text/javascript');
//              ?>
        </body>
</html>
