<?php echo $this->doctype(); echo 123; exit; ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('royal')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->heaadLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/main.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/coin-slider.js',   'text/javascript')
        ; ?>
    </head>
        <body>
             <div class='wrapper'>
                <nav>
                    <header>
                        <img class="logo" src='image/logo.png'>
                        <div class='header-menu-top'>

                           <!--  <?php echo $this->navigation($this->getNavigation());
                                ->menu()
                                ->setMinDepth(0)
                                ->setMaxDepth(0)
                                ->render(); ?> -->
                            <!-- <ul>
                                <li class='active-top'><a href="#">ГЛАВНАЯ</a></li>
                                <li>О НАС</li>
                                <li>ПОРТФОЛИО</li>
                                <li>УСЛУГИ</li>
                                <li>КОНТАКТЫ</li>
                            </ul> -->
                        </div>
                        <div class="border-slyder">
                            <div class="wrapper-slider">
                                <div class="container">
                                    <div id="slides">
                                        <img src="image/image-slider-3.jpg" />
                                        <img src="image/image-slider-3.jpg" />
                                        <img src="image/image-slider-4.jpg" />
                                        <img src="image/image-slider-5.jpg" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="menu-content ">
                            <div class='header-menu-bottom'>
                                <?php echo $this->navigation($navigationBottom)
                                    ->menu()
                                    ->setMinDepth(0)
                                    ->setMaxDepth(0)
                                    ->render(); ?>
                                <ul>
                                    <li class='active-bottom'><a href="#">покрытие для стен</a></li>
                                    <li>покрытие для пола</li>
                                    <li>двери</li>
                                    <li>меьель</li>
                                    <li>системы для дома</li>
                                </ul>
                            </div>
                        </div>
                    </header>
                </nav>
                <div class="container">
                    <?php echo $this->content; ?>
                    <hr>
                    <footer>
                        <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
                    </footer>
                </div> <!-- /container -->
                <?php echo $this->inlineScript() ?>
                <div>
        </body>
</html>
