<?php echo $this->doctype();?>
<meta charset="utf-8">

<html lang="en">
    <head>
        <?php echo $this->headTitle('royal')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php
            echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
            echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                      ->prependStylesheet($this->basePath() . '/css/main.css');
        ?>
        <!-- Scripts -->
        <?php
            echo $this->headScript()
            ->prependFile($this->basePath() . '/js/jquery.slides.min.js',   'text/javascript')
            ->prependFile($this->basePath() . '/js/jquery.min.js','text/javascript');
        ?>
    </head>
        <body>
             <div class='wrapper'>
                <nav>
                    <header>
                        <img class="logo" src='image/logo.png'>
                        <div class='header-menu-top'>
                            <?php
                                $this->navigation($this->GetNavigationHelper())->findOneByResource('2')->setActive(true);
                                echo $this->navigation()->menu()->setPartial('template/navigation_top')->render();
                            ?>
                        </div>
                        <div class="border-slyder">
                            <div class="wrapper-slider">
                                <div class="container">
                                    <div id="slides">
                                        <img src="image/image-slider-3.jpg" />
                                        <img src="image/image-slider-3.jpg" />
                                        <img src="image/image-slider-4.jpg" />
                                        <img src="image/image-slider-5.jpg" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="menu-content ">
                            <div class='header-menu-bottom'>
                                    <?php
                                        $this->navigation($this->GetNavigationHelper())->findOneByResource('2')->setActive(true);
                                        echo $this->navigation()->menu()->setPartial('template/navigation_bottom')->render();
                                    ?>
                            </div>
                        </div>
                    </header>
                </nav>
                 <div class="papirus">
                     <div class="warpper-uzor-top"><div class="uzor-top"></div></div>
                     <div class="content">
                         <div class="warpper-content">
                    <?php echo $this->content; ?>
             </div>
             <div class="uzor-down"></div>
             </div>
                 <div class="footer"></div>
                 <!-- /container -->
              <?php echo $this->inlineScript()
                  ->prependFile($this->basePath() . '/js/init.slides.js','text/javascript')
                  ->prependFile($this->basePath() . '/js/resize.border.slider.js','text/javascript');
              ?>

                <div>
        </body>
</html>
