<div class="papirus">
    <div class="warpper-uzor-top"><div class="uzor-top"></div></div>
    <div class="content">
        <div class="warpper-content">
            <div class="left-content">
                <p><span class='alegreto-font'>В</span> XXIвеке, когда самые выдающиеся открытия, инновации и изобретения остались в далеком прошлом, казалось бы, уже нет места чему-то новому, чему-то, что может удивить и добавить ярких красок в нашу жизнь. Но, из года в год, на рынке появляется что-то, без чего мы уже не представляем нашу с Вами жизнь, будь то очередной девайс от Apple или другой новомодный гаджет.</p>
                <br />
                <p><span class='alegreto-font'>Т</span>ак происходит и в области дизайна интерьеров. Чтобы реализовать даже самый неординарный замысел дизайнера или удовлетворить взыскательного покупателя производителям приходится идти в ногу со временем и выводить на рынок новые материалы, которые позволят подчеркнуть Вашу индивидуальность и создать неповторимый интерьер.</p>
                <br />
                <p><span class='alegreto-font'>М</span>ы тщательно следим за интерьерной модой и представляем Вашему вниманию не только декоративные материалы, которые остаются популярными на протяжении десятков лет, но и новинки, которые только набирают свою популярность и выводят на новый качественный уровень  дизайн интерьеров.</p>
                <br />
                <p><span class='alegreto-font'>В</span>месте с нами Вы воплотите свои самые  смелые  творческие идеи. </p>
                <br />
                <p><span class='alegreto-font'>М</span>ы работаем для Вас! </p>
                <br />
                <br />
                <p><span class='alegreto-font'>С</span> уважением,  коммерческий директор RoyalBuildingGroup</p>
                <p>Тимошенко Анна <img class='podpis' src="image/podpis.png"></p>
            </div>
            <div class="right-content">
                <img class="pero" src='image/pero.png'></img>
                <ul class="contact">
                    <li class='contact-header'>Контакты</li>
                    <li class='tel'>(099) 127 35 35</li>
                    <li class='tel'>(067) 485 09 22</li>
                    <li class='email'>royal_ua@mail.ru</li>
                    <li class='city'>г. Донецк</li>
                    <li class='adres'>пр-т Ильича 103Д</li>
                </ul>
                <div class="portfolio-blok">
                    <img class="uzor" src='image/uzor.jpg'></img>
                    <span class="work">Наши Работы</span>
                    <img class="portfollio" src='image/venzel.png'></img>
                    <a class="buttot-show" href='#'>
                        посмотреть
                    </a>
                </div>
            </div>
        </div>
        <div class="uzor-down"></div>
    </div>
</div>