<div class="left-content">

<?php foreach($SubcategoriesProductData as $key){  ?>
    <a href="/page/manufacturers/<?php echo $key['id'].'_'.$generalHelper->transliteration($key['title']); ?>"><div class="warpper-subcategories">
        <div class="border-content">
        </div>
        <img  class="subcategories-image" src="/siteDir/categories/<?php  echo $key['image'] ?>" alt=""/>
        <span class="desk-subcategories"><?php  echo $key['title'] ?></span>
    </div></a>
<?php  } ?>
</div>
<div class="right-content  page">
    <?php echo $this->render('template/hit_pay.phtml') ?>
<!--<div class="right-content  page">-->
<!--    <p class="title-pays-hit"><span class="alegreto-font">X</span ><span class="secend-part-title" >иты продаж</span></p>-->
<!--    <div class="hit-pays">-->
<!--        <div class="wrap-pays-item">-->
<!--            <div class="pays-item"></div>-->
<!--            <img src="/siteDir/product/149-1280x1024_530670699e8f4.jpg" alt=""/>-->
<!--        </div>-->
<!--        <div class="wrap-pays-item">-->
<!--            <div class="pays-item"></div>-->
<!--            <img src="/siteDir/product/149-1280x1024_530670699e8f4.jpg" alt=""/>-->
<!--        </div>-->
<!--        <div class="wrap-pays-item">-->
<!--            <div class="pays-item"></div>-->
<!--            <img src="/siteDir/product/149-1280x1024_530670699e8f4.jpg" alt=""/>-->
<!--        </div>-->
<!--        <div class="wrap-pays-item">-->
<!--            <div class="pays-item"></div>-->
<!--            <img src="/siteDir/product/149-1280x1024_530670699e8f4.jpg" alt=""/>-->
<!--        </div>-->
<!--    </div>-->
    <?php
    if(isset($page->activePage['right'])) {
        $this->navigation($this->GetNavigationHelper('right',$page->activePage['right']))
            ->findOneByResource($page->activePage['right'])->setActive(true);
    }else{
        $this->navigation($this->GetNavigationHelper('right',$page->activePage['right']));
    }
    echo $this->navigation()->menu()->setPartial('template/navigation_right')->render();
    ?>
</div>

