<div class="left-content manufacturers">
<?php foreach($productData as $key){  ?>
    <a href="/page/product/<?php echo $key['id'].'_'.$generalHelper->transliteration($key['title']); ?>"><div class="warpper-manufacturers">
            <div class="warpper-manufacturers-img">
                    <img  class="manufacturers-image" src="/siteDir/categories/<?php  echo $key['image'] ?>" alt=""/>
                    <span class="desk-product"><?php  echo $key['title'] ?></span>
            </div>
    </div></a>
<?php  } ?>
</div>
<div class="right-content  page">



    <?php echo $this->render('template/hit_pay.phtml') ?>
    <?php
    if(isset($page->activePage['right'])){
        $this->navigation($this->GetNavigationHelper('right',$page->activePage['page'],$page->activePage['right']),true)
            ->findOneByResource($page->activePage['right'])->setActive(true)
            ->findOneByResource($page->activePage['right_manufacturers'])->setActive(true);
    }else{
        $this->navigation($this->GetNavigationHelper('right',$page->activePage['right']));
    }
    echo $this->navigation()->menu()->setPartial('template/navigation_right')->render();
    ?>
</div>

