<div class="left-content pages">
<?php echo $dataPage->content; ?>
</div>
<div class="right-content">
    <img class="pero" src='/image/pero.png'>
    <ul class="contact">
        <li class='contact-header'>Контакты</li>
        <li class='tel'>(099) 127 35 35</li>
        <li class='tel'>(067) 485 09 22</li>
        <li class='email'>royal_ua@mail.ru</li>
        <li class='city'>г. Донецк</li>
        <li class='adres'>пр-т Ильича 103Д</li>
    </ul>
    <div class="portfolio-blok">
        <img class="uzor" src='/image/uzor.jpg'>
        <span class="work">Наши Работы</span>
        <img class="portfollio" src='/image/venzel.png'>
        <a class="buttot-show" href='#'>посмотреть</a>
    </div>
</div>

