

<!--<link rel="stylesheet" type="text/css" href="/css/bootstraGallery/bootstrap-image-gallery.min.css"/>-->

<link rel="stylesheet" href="/css/bootstraGallery/magnific-popup.css">

<!-- jQuery 1.7.2+ or Zepto.js 1.0+ -->


<!-- Magnific Popup core JS file -->




<div class="left-content product-description">
    <span class="title-product"><?php  echo $ProductModel->title ?></span>
    <div class="description-product" >
        <img  class="img-product" src="<?php  echo $ProductModel->main_image ?>"  style="float: left" alt=""/>
        <?php echo $ProductModel->description ?>
    </div>
    <div class="wrap-tabs-block">
        <div class="item-tubs-product active color">Цвет</div>
        <div class="item-tubs-product technical-information">Техническая информация</div>
        <div class="item-tubs-product video">Видео</div>
        <div class="item-tubs-product project">Проэкты</div>
        <div class="item-tubs-product bays">Где купить</div>


        <div class="wrap-tab-content color active">
            <div class="popup-gallery">
                <?php  foreach($colorData as $key) { ?>
                    <div class="wrap-img-color-product">
                        <a   href="<?php  echo $key['image_color'] ?>">
                            <img class="img-color-product" src="<?php  echo $key['image_color'] ?>" alt=""/>
                        </a>
                    </div>
                <?php } ?>
            </div>

            <div class="page-circle">
                <span class="circle active">&nbsp;</span>
            </div>
        </div>

        <div class="wrap-tab-content technical-information">
            <?php $file = explode(',',$ProductModel->file);
           if($file[0]){
            for($i=0;$i<count($file);$i++){ ?>
                <a href="/page/download/?file=<?php echo $file[$i] ?>">Скачать</a>
            <?php }} ?>


            <?php echo $ProductModel->technical_description ?>
        </div>
        <div class="wrap-tab-content video">
            <?php $videoData = explode(',',$ProductModel->video);
                for($i=0;$i<count($video);$i++){ ?>
                <iframe class="video-frame" src="//www.youtube.com/embed/<?php echo $video[$i] ?>" frameborder="0" allowfullscreen></iframe>
            <?php } ?>
        </div>
        <div class="wrap-tab-content project">
            <div class="popup-gallery-project">
               <div class="wrap-img-color-product">
                    <a   href="<?php  echo '/siteDir/product/large/'.basename($ProductModel->main_image) ?>">
                        <img class="img-color-product" src="<?php  echo $ProductModel->main_image ?>" alt=""/>
                    </a>
                </div>

                <?php $imageData =explode(',',$ProductModel->image);
                if(!empty($imageData[0])){
                foreach($imageData as $key=>$value) { ?>
                    <div class="wrap-img-color-product">
                        <a   href="<?php  echo '/siteDir/product/large/'.basename($value) ?>">
                            <img class="img-color-product" src="<?php  echo $value ?>" alt=""/>
                        </a>
                    </div>
                <?php }} ?>
            </div>
        </div>

        <div class="wrap-tab-content bays">

        </div>

    </div>

</div>

<div class="right-content  page">

        <?php echo $this->render('template/hit_pay.phtml') ?>

    <?php
    if(isset($page->activePage['right'])){
        $this->navigation($this->GetNavigationHelper('right',$page->activePage['page'],$page->activePage['right']),true)
            ->findOneByResource($page->activePage['right'])->setActive(true)
            ->findOneByResource($page->activePage['right_manufacturers'])->setActive(true);
    }else{
        $this->navigation($this->GetNavigationHelper('right',$page->activePage['right']));
    }
    echo $this->navigation()->menu()->setPartial('template/navigation_right')->render();
    ?>
</div>


<script src="/js/bootstraGallery/jquery.magnific-popup.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){

        $(document).on('click','.item-tubs-product',function(){
            var classActiveBlock = $(this).attr('class').split(' ')[1];
            $('.item-tubs-product.active').removeClass('active');
            $('.wrap-tab-content.active').removeClass('active');
            $('.'+classActiveBlock).addClass('active');
        })

        $(document).ready(function() {
            $('.popup-gallery').magnificPopup({
                delegate: 'a',
                type: 'image',
                tLoading: 'Loading image #%curr%...',
                mainClass: 'mfp-img-mobile',
                gallery: {
                    enabled: true,
                    navigateByImgClick: true,
                    preload: [0,1] // Will preload 0 - before current, and 1 after the current image
                },
                image: {
                    tError: '<a href="%url%">The image #%curr%</a> could not be loaded.',
                    titleSrc: function(item) {
                        return item.el.attr('title') + '<small>by Marsel Van Oosten</small>';
                    }
                }
            });
        });

        $(document).ready(function() {
            $('.popup-gallery-project').magnificPopup({
                delegate: 'a',
                type: 'image',
                tLoading: 'Loading image #%curr%...',
                mainClass: 'mfp-img-mobile',
                gallery: {
                    enabled: true,
                    navigateByImgClick: true,
                    preload: [0,1] // Will preload 0 - before current, and 1 after the current image
                },
                image: {
                    tError: '<a href="%url%">The image #%curr%</a> could not be loaded.',
                    titleSrc: function(item) {
                        return item.el.attr('title') + '<small>by Marsel Van Oosten</small>';
                    }
                }
            });
        });

    })
</script>

<!--<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>-->
<!--<script src="http://blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>-->
<!--<script type="text/javascript" src="/js/bootstraGallery/bootstrap-image-gallery.min.js"></script>-->

