<link rel="stylesheet" type="text/css" href="http://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css" />
<link rel="stylesheet" type="text/css" href="/css/jInputFile.css" />
<link rel="stylesheet" type="text/css" href="/css/palitra.css" />
<script type="text/javascript" src="/js/ckeditor3/ckeditor.js"></script>
<script type="text/javascript" src="/js/palitra.js"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>


<div class="left-content addProduct">
<!--<iframe width="420" height="315" src="//www.youtube.com/embed/zccCTfN_b6Q" frameborder="0" allowfullscreen></iframe>-->
<!--<div id="map"></div>-->
    <?php echo $this->form()->openTag($formAdd);?>

                <div class="group-form">
                    <div class="wrapper-input title">
                        <?php echo $this->formRow($formAdd->get('title')) ?>
                    </div>
                    <div class="wrapper-input id_manufacturers">
                        <?php echo $this->formRow($formAdd->get('id_manufacturers')) ?>
                    </div>
                    <div class="wrapper-input price">
                        <?php echo $this->formRow($formAdd->get('price')) ?>
                    </div>
                    <div class="wrapper-input count">
                        <?php echo $this->formRow($formAdd->get('count')) ?>
                    </div>
                    <div class="wrapper-input description">
                        <?php echo $this->formRow($formAdd->get('description')->setAttribute('class','ckeditor')) ?>
                    </div>
                    <?php echo $this->formRow($formAdd->get('image')) ?>
                    <div class="wrapper-input video">
                        <?php echo $this->formRow($formAdd->get('video')) ?>
                    </div>
                    <div class="wrapper-input addres_buy">
                        <?php echo $this->formRow($formAdd->get('addres_buy')) ?>
                    </div>
                    <?php echo $this->formRow($formAdd->get('id_categories_product')->setValue($categories_product_id)); ?>
                    <?php echo $this->formRow($formAdd->get('id_subcategories_product')->setValue($id_subcategories_product)); ?>
                        <p>Добавить  изображение</p>
                    <hr>
                    <div class="wrapper-input image" >
                        <div class="wrapper-image">
                            <img  width="100" height="100" class="prewiew-defult" src=""/>
                            <input  type="file" name="img-file[]" multiple class="image-file" >
                        </div>
                    </div>
                    <p>Добавить  PDF</p>
                    <hr>
                    <div class="wrapper-input file">
                        <div class="wrapper-image file">
                            <div class="prewiew-defult-pdf ">
                                <span class="pdf-title">
                                </span>
                            </div>
                        </div>
                        <input  type="file" name="pdf-file[]"  multiple id="file-pdf" >
                        <div class="wrapper-input file">
                            <?php echo $this->formRow($formAdd->get('file')->setAttribute('id','file-pdf-input')) ?>
                        </div>
                    </div>

                    <p>Добавте цвет</p>
                    <hr>
                    <div class="container palitra">
                        <div class="wrraper-pallitra">
                            <div class="preview"></div>
                            <div class="colorpicker" style="display:none">
                                <canvas id="picker" var="2" width="300" height="300"></canvas>
                                <div class="controls">
                                    <div><label>R</label> <input type="text" id="rVal" /></div>
                                    <div><label>G</label> <input type="text" id="gVal" /></div>
                                    <div><label>B</label> <input type="text" id="bVal" /></div>
                                    <div><label>RGB</label> <input type="text" id="rgbVal" /></div>
                                    <div><label>HEX</label> <input type="text" id="hexVal" /></div>
                                </div>
                            </div>
                        </div>
                        <div class="wrraper-pallitra">
                            <div class="preview"></div>
                            <div class="colorpicker" style="display:none">
                                <canvas id="picker" var="2" width="300" height="300"></canvas>
                                <div class="controls">
                                    <div><label>R</label> <input type="text" id="rVal" /></div>
                                    <div><label>G</label> <input type="text" id="gVal" /></div>
                                    <div><label>B</label> <input type="text" id="bVal" /></div>
                                    <div><label>RGB</label> <input type="text" id="rgbVal" /></div>
                                    <div><label>HEX</label> <input type="text" id="hexVal" /></div>
                                </div>
                            </div>
                        </div>
                        <div class="green-cross"></div>
                    </div>
        <button form="addProduct" class="addProduct" name="edit">Добавить продукт</button>
        <?php echo $this->form()->closeTag($formAdd);?>
</div>
<div class="container-crop" style="display:none;">
    <div class="row">
        <div class="span12">
            <div class="jc-demo-box">
                <img src="" id="target" alt="crop wait" />
                <div class="clearfix"></div>
                <form id="coords" class="coords" onsubmit="return false;" >
                    <div class="inline-labels">
                        <input  type="hidden" size="4" id="x1" name="x1" />
                        <input  type="hidden" size="4" id="y1" name="y1" />
                        <input  type="hidden" size="4" id="x2" name="x2" />
                        <input  type="hidden" size="4" id="y2" name="y2" />
                        <input  type="hidden" size="4" id="w" name="w" />
                        <input  type="hidden" size="4" id="h" name="h" />
                    </div>
                    <button id="crop-image"  class="green">загрузить</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
globalNameImage = [];
globalNamePdf = [];
globalK = 0;
globalEvent = '';


    $(function() {
        $(document).ready(function(){
            $('.image-file').jInputFile();
            $('#file-pdf').jInputFile();
        });



        $( "#sort-form " ).sortable({
            stop: function( event, ui) {
                $('#sort-form .ech').each(function(i, elm){
                    $(elm).find('.number').val(i+1);
                });

            }
        });
        $( "#sort-form" ).disableSelection();
    });

    $(function () {


        var image = $('.image-file').fileupload({
            url: '/admin/uploadImage',
            dataType: 'json',
            multipart:true,
            done: function (e, data) {
                globalNameImage.push(data.result);
                    if(data.originalFiles.length == globalNameImage.length){
                        globalEvent = e;
                        cropImage(globalNameImage)
                    }
            },
            progressall: function (e, data) {
                var progress = parseInt(data.loaded / data.total * 100, 10);
                $('.progress').css(
                    'width',
                    progress + '%'
                );
            }


        });


         $('#file-pdf').fileupload({
            url: '/admin/uploadPdf',
            dataType: 'json',
            multipart:true,
            done: function (e, data) {

                globalNamePdf.push(data.result);
                console.log(globalNamePdf.join(','));
                if(data.originalFiles.length == globalNamePdf.length){
                    $('.file').val(globalNamePdf.join(','));
                }
            },
            progressall: function (e, data) {
                var progress = parseInt(data.loaded / data.total * 100, 10);
                $('.progress').css(
                    'width',
                    progress + '%'
                );
            }


        });

    });

$(document).ready(function(){


    var imgView = $('.image').val();
    if(imgView !=''){
        var arrImg = [];
        arrImg = imgView.split(',');
        for(var i= 0;i<arrImg.length;i++){
            var cloneElement = $(".prewiew-defult").clone();
            $(cloneElement).attr('src',"/tmp/"+arrImg[i]);
            $(cloneElement).attr('class',"prewiew");
            $(cloneElement).css({margin:'5px',border:'solid 2px black'});
            $('.wrapper-input.image').append(cloneElement);

        }
    }

    var fileView = $('#file-pdf-input').val();

    if(fileView !=''){
        var arrfile = [];
        arrfile = fileView.split(',');

        if(arrfile.length==1){

            var cloneElement = $(".prewiew-defult-pdf").clone();
            $(cloneElement).find('.pdf-title').text(fileView);
            var url = '/image/pdf.png';
            $(cloneElement).css('background-image', 'url(' + url + ')');

            $('.wrapper-image.file').append(cloneElement);

        }else{

            for(var i= 0;i<arrfile.length;i++){

                var cloneElement = $(".prewiew-defult-pdf").clone();
                $(cloneElement).find('.pdf-title').text(arrfile[i]);
                var url = '/image/pdf.png';
                $(cloneElement).css('background-image', 'url(' + url + ')');
    //            $(cloneElement).css({'background-image': 'url('+url+')'});
                $('.wrapper-image.file').append(cloneElement);


            }
        }
    }

//           $.getJSON(
//            'http://maps.googleapis.com/maps/api/geocode/json?address='+encodeURIComponent('Украина, г. Донецк, ул. Собинова 2а')+'&sensor=true',
//            {
//                address:'Украина, г. Донецк, ул. Собинова 2а',
//                sensor:true
//            },

//         function(data){
//
//          lat = data.results[0].geometry.location.lat;
//           lng = data.results[0].geometry.location.lng;
//             var myOptions = {
//                 center: new google.maps.LatLng(lat,lng),
//                 zoom: 10,
//                 mapTypeId: google.maps.MapTypeId.ROADMAP
//             };
//             var map = new google.maps.Map(document.getElementById("map"), myOptions);
//
//             var addressArray = new Array("Украина, г. Донецк, ул. Собинова 2а", "Украина г. Донецк, ул. Артема 1");
//             var geocoder = new google.maps.Geocoder();
//
//             for (var i = 0; i < addressArray.length; i++) {
//
//                 geocoder.geocode( { 'address': addressArray[i]}, function(results, status) {
//                     console.log(results[0].formatted_address);
//                     if (status == google.maps.GeocoderStatus.OK) {
//                         var marker = new google.maps.Marker({
//                             map: map,
//                             position: results[0].geometry.location,
//                             title: results[0].formatted_address,
//                             labelContent: "$425K",
//                             labelAnchor: new google.maps.Point(22, 0),
//                             labelClass: "googleLabels", // the CSS class for the label
//                             labelStyle: {opacity: 0.75}
//
//                         });
//
//                         var iw = new google.maps.InfoWindow({
//                             content: results[0].formatted_address
//                         });
//                         google.maps.event.addListener(marker, "click", function (e) { iw.open(map, this); });
//                     } else {
//                         alert("Geocode was not successful for the following reason: " + status);
//                     }
//                 });
//             }
//
//            });
});

    $(document).on('click','#crop-image',function(){

    var sendData = {};
        sendData.x1 =  $('#x1').val();
        sendData.x2 =  $('#x2').val();
        sendData.y2 =  $('#y2').val();
        sendData.y1 =  $('#y1').val();
        sendData.w =  $('#w').val();
        sendData.h =  $('#h').val();
        sendData.width  = $('#target').width();
        sendData.height  = $('#target').height();
        sendData.imageName  = globalNameImage[globalK];
        sendData.data  = $('#target').attr('data-cof');

        $.post('/admin/crop',sendData)
            .done(function(e,data){
                var cloneElement = $(".prewiew-defult").clone();
                $(cloneElement).attr('src',"/tmp/"+e);
                $(cloneElement).attr('class',"prewiew");
                $(cloneElement).css({margin:'5px',border:'solid 2px black'});
                $( ".container-crop" ).dialog( "close" );

                if($('input.image').val()==''){
                    $('input.image').val(globalNameImage[globalK]);
                }else{
                    $('input.image').val($('input.image').val()+','+globalNameImage[globalK]);
                }

                $('#target').imgAreaSelect({remove: true});
                globalK++;
                $('.wrapper-input.image').append(cloneElement);
                if(globalLength>globalK){
                    cropImage(globalNameImage)
                }else{

                    globalNameImage = [];
                    globalK = 0;
                    globalEvent ='' ;
                    globalLength = '';
                }

            });

    });



    function cropImage(name){

    globalLength = name.length;

            var i  = $(globalEvent.target).attr('data-iterator');

            if(typeof i=='undefined'){

                $('input').removeClass('active-input');
//                $('.image').val(name[globalK]);
                $('.image').addClass('active-input');

            }else{

                $('input').removeClass('active-input');
                $('input[name="image_'+i+'"]').addClass('active-input');
                $('input[name="image_'+i+'"]').val(name[globalK]);
                globalNameInput = i;

            }
            var newimage = new Image();
            newimage.src = '\\tmp\\'+name[globalK];
            newimage.onload = function(){

                var width  =   this.naturalWidth;
                var height =   this.naturalHeight;
                var flag = false;
                var heightScreen;
                var widthScreen;
                var n1;
                var n2;
                var cof;
                heightScreen = screen.width;
                widthScreen = screen.height;
                if ((heightScreen < height) || (widthScreen < width)) {
                    flag = 1;
                    var  i = 0;
                    while (1) {
                        n1 =  width /  height;
                        n2 =  height /  width;
                        if ( n1 > 1) {
                            cof =  n1;
                        } else {
                            cof =  n2;
                        }

                        if (( heightScreen <  height) || ( widthScreen <  width)) {
                            width =  width /  cof;
                            height =  height /  cof;

                        } else {

                            break;
                        }
                    }
                }

                $('#target').css({'width':width,'height':height});
                $('#target').attr('src',this.src);
                $('#target').attr('data-cof', i+' '+cof);

            };

            $(".container-crop").dialog(({
                height: "auto",
                width: 'auto',
                dialogClass:'uploader',
                closeOnEscape: false, draggable: false, zIndex: "100", position: "left top"
    //                close: function(ev, ui) { $('#target').imgAreaSelect({remove: true});  $(this).close();  }
            }));



        $('#target').imgAreaSelect({
            x1: 0, y1: 0, x2: 50, y2: 50,
            aspectRatio: '1:1',
            handles: true,
            zIndex: 1000000,
            minHeight: 50,
            minWidth: 50,
            onInit: function(img, selection) {

                $("#x1").val(0);
                $("#y1").val(0);
                $("#x2").val(50);
                $("#y2").val(50);
                $("#w").val(50);
                $("#h").val(50);
            },
            onSelectEnd: function(img, selection) {

                $("#x1").val(selection.x1);
                $("#y1").val(selection.y1);
                $("#x2").val(selection.x2);
                $("#y2").val(selection.y2);
                $("#w").val(selection.width);
                $("#h").val(selection.height);

            }
        });
        }



    (function($) {
        $.fn.jInputFile = function(options) {

            return this.each(function() {

                $(this).val('');
                $(this).wrap('<div></div>');
                $(this).parent().css('height', $(this).height());
                $(this).after('<div class="jInputFile-fakeButton"></div><div class="jInputFile-blocker"></div><div class="jInputFile-activeBrowseButton jInputFile-fakeButton"></div><div class="jInputFile-fileName"></div>');
                $(this).addClass('jInputFile-customFile');

                $(this).hover(
                    function () {
                        $(this).parent().children('.jInputFile-activeBrowseButton').css('display', 'block');
                    },
                    function () {
                        $(this).parent().children('.jInputFile-activeBrowseButton').css('display', 'none');
                    }
                );

                $(this).change(function(){
                    var file = $(this).val();

                    //Находим название файла и его расширение
                    var reWin = /.*\\(.*)/;
                    var fileName = file.replace(reWin, '$1');
                    var reUnix = /.*\/(.*)/;
                    fileName = fileName.replace(reUnix, '$1');
                    var regExExt =/.*\.(.*)/;
                    var ext = fileName.replace(regExExt, '$1');

                    //Показываем значок и имя файла
                    var pos;
                    if (ext){
                        switch (ext.toLowerCase()) {
                            case 'doc': pos = '0'; break;
                            case 'bmp': pos = '16'; break;
                            case 'jpg': pos = '32'; break;
                            case 'jpeg': pos = '32'; break;
                            case 'png': pos = '48'; break;
                            case 'gif': pos = '64'; break;
                            case 'psd': pos = '80'; break;
                            case 'mp3': pos = '96'; break;
                            case 'wav': pos = '96'; break;
                            case 'ogg': pos = '96'; break;
                            case 'avi': pos = '112'; break;
                            case 'wmv': pos = '112'; break;
                            case 'flv': pos = '112'; break;
                            case 'pdf': pos = '128'; break;
                            case 'exe': pos = '144'; break;
                            case 'txt': pos = '160'; break;
                            default: pos = '176'; break
                        };
                        $(this).parent().children('.jInputFile-fileName').html(fileName).css({'background-position':('0px -'+pos+'px'),'background-repeat':'no-repeat', 'display':'block'});
                    };
                });
            });
        }
    })(jQuery);



</script>



