<div class="left-content">
    Редактировать категории
    <hr>
    <?php echo $this->form()->openTag($formEdit);?>
    <div id="sort-form">
        <?php  for($i=0;$i<$formEdit->countInput;$i++){ ?>
            <div class="ech">
                <div class="wrapper-input title">
                    <?php echo $this->formRow($formEdit->get('title_'.$i)) ?>
                </div>
                <div class="wrapper-input visible">
                    <?php echo $this->formRow($formEdit->get('visible_'.$i)) ?>
                </div>
                <div class="wrapper-input number">
                    <?php echo $this->formRow($formEdit->get('number_'.$i)) ?>
                </div>
                <div class="wrapper-input id">
                    <?php echo $this->formRow($formEdit->get('id_'.$i)) ?>
                </div>

                <hr>
            </div>

        <?php } ?>
    </div>
    <button form="editCategory" name="edit">Редактировать</button>
    <?php echo $this->form()->closeTag($formEdit);?>
    <br />
    <p>Добавить категорию</p>
    <hr>
    <?php echo $this->form()->openTag($formAdd);?>
            <div class="wrapper-input">
                <?php echo $this->formRow($formAdd->get('title')) ?>
            </div>
            <div class="wrapper-input">
                <?php echo $this->formRow($formAdd->get('visible')) ?>
            </div>
            <div class="wrapper-input">
                <?php echo $this->formRow($formAdd->get('number')) ?>
            </div>
            <div class="wrapper-input">
                <?php echo $this->formRow($formAdd->get('id')) ?>
            </div>
    <button form="addCategory" name="add" >Добавить</button>
    <?php echo $this->form()->closeTag($formAdd);?>

</div>

<script type="text/javascript">
    $(function() {
        $( "#sort-form " ).sortable({
            stop: function( event, ui) {

                $('#sort-form .ech').each(function(i, elm){
                    $(elm).find('.number').val(i+1);
                });

            }
        });
        $( "#sort-form" ).disableSelection();
    });
</script>



