<link rel="stylesheet" type="text/css" href="http://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css"/>
<link rel="stylesheet" type="text/css" href="/css/jInputFile.css"/>
<link rel="stylesheet" type="text/css" href="/css/palitra.css"/>
<script type="text/javascript" src="/js/ckeditor3/ckeditor.js"></script>
<script type="text/javascript" src="/js/palitra.js"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>


<div class="left-content addProduct">
<!--<iframe width="420" height="315" src="//www.youtube.com/embed/zccCTfN_b6Q" frameborder="0" allowfullscreen></iframe>-->
<!--<div id="map"></div>-->

<?php echo $this->form()->openTag($formAdd); ?>

<?php echo $this->formRow($formAdd->get('image')) ?>
<?php echo $this->formRow($formAddColor->get('image_color')->setAttribute('id', 'image-color')) ?>
<?php echo $this->formRow($formAddColor->get('color')->setAttribute('id', 'input-color')) ?>
<?php echo $this->formRow($formAdd->get('file')->setAttribute('id', 'file-pdf-input')) ?>
<?php echo $this->formRow($formAdd->get('main_image')->setAttribute('id','main_image')) ?>
<?php echo $this->formRow($formAdd->get('id')->setAttribute('id','id_product')) ?>

<div class="group-form">
    <div class="wrapper-input title">
        <?php echo $this->formRow($formAdd->get('title')) ?>
    </div>
    <div class="wrapper-input id_categories_product">
        <?php echo $this->formRow($formAdd->get('id_categories_product')); ?>
    </div>
    <div class="wrapper-input id_subcategories_product">
        <?php echo $this->formRow($formAdd->get('id_subcategories_product')); ?>
    </div>
    <div class="wrapper-input id_manufacturers">
        <?php echo $this->formRow($formAdd->get('id_manufacturers')) ?>
    </div>
    <div class="wrapper-input price">
        <?php echo $this->formRow($formAdd->get('price')) ?>
    </div>
    <div class="wrapper-input description">
        <?php echo $this->formRow($formAdd->get('description')->setAttribute('class', 'ckeditor')) ?>
    </div>
    <div class="wrapper-input description">
        <?php echo $this->formRow($formAdd->get('technical_description')->setAttribute('class', 'ckeditor')) ?>
    </div>
    <?php echo $this->formRow($formAdd->get('image')->setAttribute('id','image-file')) ?>
    <div class="wrapper-input video">
        <?php echo $this->formRow($formAdd->get('video')) ?>
    </div>
    <div class="wrapper-input addres_buy">
        <?php echo $this->formRow($formAdd->get('addres_buy')) ?>
    </div>
    <p>Добавить изображение</p>
    <hr>
    <div class="wrapper-input image">
        <div class="wrapper-image">
            <div class="image-warrper-file">
                <img width="100" height="100" class="prewiew-defult" src=""/>
            </div>
            <input type="file" name="img-file[]" multiple class="image-file">
        </div>
    </div>
    <p>Добавить PDF</p>
    <hr>
    <div class="wrapper-input file">
        <div class="wrapper-image inner">
            <div class="wrapper-image file-defoult" style="display: none">
                <span class="pdf-title"></span>
                <div class="prewiew-defult-pdf "></div>
            </div>

        </div>
        <input type="file" name="pdf-file[]" multiple id="file-pdf">
    </div>
    <p>Добавте цвет</p>
    <hr>
    <div class="wrapper-input color">
        <div class="wrapper-image">
            <div class="image-warrper-color">
                <img width="100" height="100" class="prewiew-defult-color" src=""/>
            </div>
            <input type="file" name="img-file-color[]" multiple class="image-file-color">
        </div>
    </div>
    <button form="addProduct" class="addProduct" name="edit">Добавить продукт</button>

    <?php echo $this->form()->closeTag($formAdd); ?>
</div>
<div class="container-crop" style="display:none;">
    <div class="row">
        <div class="span12">
            <div class="jc-demo-box">
                <img src="" id="target" alt="crop wait"/>

                <div class="clearfix"></div>
                <form id="coords" class="coords" onsubmit="return false;">
                    <div class="inline-labels">
                        <input type="hidden" size="4" id="x1" name="x1"/>
                        <input type="hidden" size="4" id="y1" name="y1"/>
                        <input type="hidden" size="4" id="x2" name="x2"/>
                        <input type="hidden" size="4" id="y2" name="y2"/>
                        <input type="hidden" size="4" id="w" name="w"/>
                        <input type="hidden" size="4" id="h" name="h"/>
                    </div>
                    <button id="crop-image" class="green">загрузить</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">


globalNameImage = [];
globalNamePdf = [];
globalK = 0;
globalEvent = '';
globalNamePdf.ext = [];
globalType = 'image';

$(document).ready(function () {
    $('.image-file').jInputFile();
    $('.image-file-color').jInputFile();
    $('#file-pdf').jInputFile();
});

$(document).on('change','select[name="id_categories_product"]',function() {
    var name = $(this).attr('name');
    var value = $(this).val();
    $.post('/admin/getSubcategories',{name : name,value : value})
        .done(function(data) {
            data = JSON.parse(data);
            var options = "<option value>Выберете подкатегорию</option>";
            for(var i=0;i<data.length;i++){
                options += '<option value="' + data[i].id + '">' + data[i].title + '</option>';
            }
            $('select[name="id_subcategories_product"]').html(options);

        });
});
$(document).on('change','select[name="id_subcategories_product"]',function() {
    var name = $(this).attr('name');
    var value = $(this).val();
    $.post('/admin/getManufacturers',{name : name,value : value})
        .done(function(data) {
            data = JSON.parse(data);
            var options = "<option value>Выберете производителя</option>";
            for(var i=0;i<data.length;i++){
                options += '<option value="' + data[i].id + '">' + data[i].title + '</option>';
            }
            $('select[name="id_manufacturers"]').html(options);

        });
});


$(document).on('change','select[name="id_manufacturers"]',function() {
    var name = $(this).attr('name');
    var value = $(this).val();
    $.post('/admin/getGroupProduct',{name : name,value : value})
        .done(function(data) {
            data = JSON.parse(data);
            var options = "<option value>Выберете группу</option>";
            for(var i=0;i<data.length;i++){
                options += '<option value="' + data[i].id + '">' + data[i].title + '</option>';
            }
            $('select[name="id_group_product"]').html(options);

        });
});



function createPreviewFile() {
    $('.pdf-fake').remove();
    var fileView = $('#file-pdf-input').val();
    var url;
    if (fileView != '') {
        var arrfile = [];
        arrfile = fileView.split(',');
            for (var i = 0; i < arrfile.length; i++) {

                var cloneElement = $(".wrapper-image.file-defoult").clone();
                $(cloneElement).find('.pdf-title').text(arrfile[i]);
                $(cloneElement).attr('class', 'pdf-fake deleted-file');
                $(cloneElement).css({'display': 'inline-block'});
                var extFile = arrfile[i].split('.')[arrfile[i].split('.').length - 1];
                if (extFile == 'xls' || extFile == 'xlsx') {
                    url = '/image/xls.jpg';
                } else if (extFile == 'pdf') {
                    url = '/image/pdf.png';
                }
                $(cloneElement).find('.prewiew-defult-pdf').css('background-image', 'url(' + url + ')');
                $('.wrapper-image.inner').append(cloneElement);

        }
    }
}

function createPreviewImage(){

    var imgView = $('.image').val();
    if (imgView != '') {

        var arrImg = [];
        arrImg = imgView.split(',');
        for (var i = 0; i < arrImg.length; i++) {

            var cloneElement = $(".image-warrper-file").clone();
            $(cloneElement).find('.prewiew-defult').attr('src',arrImg[i]);
            $(cloneElement).find('.prewiew-defult').attr('class', "prewiew deleted-image");
            $(cloneElement).attr('class','fake');
            $(cloneElement).css({margin: '5px'});

            $(cloneElement).css({display:'inline-block'});
            $('.wrapper-input.image').append(cloneElement);

        }
    }
    if($('.main_image').val()!=''){

        var cloneElement = $(".image-warrper-file").clone();
        $(cloneElement).find('.prewiew-defult').attr('src',$('.main_image').val());
        $(cloneElement).find('.prewiew-defult').attr('class', "prewiew deleted-image main-image");
        $(cloneElement).attr('class','fake');
        $(cloneElement).css({display:'inline-block'});
        $('.wrapper-input.image').append(cloneElement);

    }

}


$(function () {

    $("#sort-form ").sortable({
        stop: function (event, ui) {
            $('#sort-form .ech').each(function (i, elm) {
                $(elm).find('.number').val(i + 1);
            });

        }
    });

    $("#sort-form").disableSelection();
});

$(function () {

    var image = $('.image-file').fileupload({
        url: '/admin/uploadImage',
        dataType: 'json',
        multipart: true,
        done: function (e, data) {
            globalNameImage.push(data.result);
            if (data.originalFiles.length == globalNameImage.length) {
                globalEvent = e;
                cropImage(globalNameImage)
            }
        },
        progressall: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('.progress').css(
                'width',
                progress + '%'
            );
        }
    });


    $('.image-file-color').fileupload({
        url: '/admin/uploadImageColor',
        dataType: 'json',
        multipart: true,
        done: function (e, data) {
            globalNameImage.push(data.result);
            globalType = 'color';

            if (data.originalFiles.length == globalNameImage.length) {
                globalEvent = e;
                cropImage(globalNameImage)
            }
        },
        progressall: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('.progress').css(
                'width',
                progress + '%'
            );
        }
    });


    $('#file-pdf').fileupload({
        url: '/admin/uploadFile',
        dataType: 'json',
        multipart: true,
        formAcceptCharset: 'utf-8',
        done: function (e, data) {

            globalNamePdf.push(data.result);

            if (data.originalFiles.length == globalNamePdf.length) {

                var value = $('#file-pdf-input').val();

                if ($('#file-pdf-input').val() == '') {

                    $('#file-pdf-input').val(globalNamePdf.join(','));
                    createPreviewFile();
                    globalNamePdf = [];

                } else {

                    $('#file-pdf-input').val(value + ',' + globalNamePdf.join(','));
                    createPreviewFile();
                    globalNamePdf = [];

                }
            }
        },
        progressall: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('.progress').css(
                'width',
                progress + '%'
            );
        }
    });

});

$(document).ready(function () {
    $(function(){
        createPreviewFile();
        createPreviewImage();
        createPreviewImageColor();
    });

//           $.getJSON(
//            'http://maps.googleapis.com/maps/api/geocode/json?address='+encodeURIComponent('Украина, г. Донецк, ул. Собинова 2а')+'&sensor=true',
//            {
//                address:'Украина, г. Донецк, ул. Собинова 2а',
//                sensor:true
//            },

//         function(data){
//
//          lat = data.results[0].geometry.location.lat;
//           lng = data.results[0].geometry.location.lng;
//             var myOptions = {
//                 center: new google.maps.LatLng(lat,lng),
//                 zoom: 10,
//                 mapTypeId: google.maps.MapTypeId.ROADMAP
//             };
//             var map = new google.maps.Map(document.getElementById("map"), myOptions);
//
//             var addressArray = new Array("Украина, г. Донецк, ул. Собинова 2а", "Украина г. Донецк, ул. Артема 1");
//             var geocoder = new google.maps.Geocoder();
//
//             for (var i = 0; i < addressArray.length; i++) {
//
//                 geocoder.geocode( { 'address': addressArray[i]}, function(results, status) {
//                     console.log(results[0].formatted_address);
//                     if (status == google.maps.GeocoderStatus.OK) {
//                         var marker = new google.maps.Marker({
//                             map: map,
//                             position: results[0].geometry.location,
//                             title: results[0].formatted_address,
//                             labelContent: "$425K",
//                             labelAnchor: new google.maps.Point(22, 0),
//                             labelClass: "googleLabels", // the CSS class for the label
//                             labelStyle: {opacity: 0.75}
//
//                         });
//
//                         var iw = new google.maps.InfoWindow({
//                             content: results[0].formatted_address
//                         });
//                         google.maps.event.addListener(marker, "click", function (e) { iw.open(map, this); });
//                     } else {
//                         alert("Geocode was not successful for the following reason: " + status);
//                     }
//                 });
//             }
//
//            });
});

$(document).on('click', '#crop-image', function () {

    var sendData = {};
    sendData.x1 = $('#x1').val();
    sendData.x2 = $('#x2').val();
    sendData.y2 = $('#y2').val();
    sendData.y1 = $('#y1').val();
    sendData.w = $('#w').val();
    sendData.h = $('#h').val();
    sendData.width = $('#target').width();
    sendData.height = $('#target').height();
    sendData.imageName = globalNameImage[globalK];
    sendData.data = $('#target').attr('data-cof');
    sendData.marker = 1;
    if(globalType=='color'){
        sendData.mainColor = 1;
        sendData.large =0;
    }else{
        sendData.large = 1;
        sendData.mainColor = 0;
    }
    $.post('/admin/crop', sendData)
        .done(function (e, data) {
            e =JSON.parse(e);

            if(globalType == 'image'){

                var cloneElement = $(".prewiew-defult").clone();
                $(cloneElement).attr('src', "/tmp/" + e.imageName);
                $(cloneElement).attr('class', "prewiew deleted-image");

            }else{

                var cloneElement = $(".prewiew-defult-color").clone();
                $(cloneElement).attr('src', "/tmp/" + e.imageName);
                $(cloneElement).attr('class', "prewiew deleted-image-color");

            }
            $(".container-crop").dialog("close");
            if ($('input.image').val() == '' && globalType =='image') {

                $('input.image').val('/tmp/'+globalNameImage[globalK]);

            } else if($('input.image').val() != ''&& globalType =='image'){

                $('input.image').val($('input.image').val() + ',' + '/tmp/'+globalNameImage[globalK]);

            } else if(typeof  e.color!="undefined" && $('#image-color').val()==''){

                $('#image-color').val('/tmp/'+globalNameImage[globalK]);
                $('#input-color').val(e.color);

            }else if(typeof  e.color!="undefined" && $('#image-color').val()!=''){

                $('#image-color').val($('#image-color').val()+','+'/tmp/'+globalNameImage[globalK]);
                $('#input-color').val($('#input-color').val()+','+e.color);

            }
            $('#target').imgAreaSelect({remove: true});
            globalK++;
            if(globalType == 'image'){
                $('.wrapper-input.image').append(cloneElement);
            }else{
                $('.wrapper-input.color').append(cloneElement);
            }
            if (globalLength > globalK) {

                cropImage(globalNameImage);

            } else {

                globalNameImage = [];
                globalK = 0;
                globalEvent = '';
                globalLength = '';
                globalType = 'image';
            }

        });

});

function createPreviewImageColor(){

    var imgView = $('#image-color').val();
    if (imgView != '') {

        var arrImg = [];
        arrImg = imgView.split(',');
        for (var i = 0; i < arrImg.length; i++) {
            var cloneElement = $(".image-warrper-color").clone();
            $(cloneElement).find('.prewiew-defult-color').attr('src',arrImg[i]);
            $(cloneElement).find('.prewiew-defult-color').attr('class', "prewiew deleted-color");
            $(cloneElement).attr('class','fake-color');
            $(cloneElement).css({margin: '5px'})
            $(cloneElement).css({display:'inline-block'});
            $('.wrapper-input.color').append(cloneElement);
        }
    }
}

function cropImage(name) {

    globalLength = name.length;

    var i = $(globalEvent.target).attr('data-iterator');

    if (typeof i == 'undefined') {

        $('input').removeClass('active-input');
//                $('.image').val(name[globalK]);
        $('.image').addClass('active-input');

    } else {

        $('input').removeClass('active-input');
        $('input[name="image_' + i + '"]').addClass('active-input');
        $('input[name="image_' + i + '"]').val(name[globalK]);
        globalNameInput = i;

    }
    var newimage = new Image();
    newimage.src = '\\tmp\\' + name[globalK];
    newimage.onload = function () {

        var width = this.naturalWidth;
        var height = this.naturalHeight;
        var flag = false;
        var heightScreen;
        var widthScreen;
        var n1;
        var n2;
        var cof;
        heightScreen = screen.width;
        widthScreen = screen.height;
        if ((heightScreen < height) || (widthScreen < width)) {
            flag = 1;
            var i = 0;
            while (1) {
                n1 = width / height;
                n2 = height / width;
                if (n1 > 1) {
                    cof = n1;
                } else {
                    cof = n2;
                }

                if (( heightScreen < height) || ( widthScreen < width)) {
                    width = width / cof;
                    height = height / cof;

                } else {

                    break;
                }
            }
        }

        $('#target').css({'width': width, 'height': height});
        $('#target').attr('src', this.src);
        $('#target').attr('data-cof', i + ' ' + cof);

    };

    $(".container-crop").dialog(({
        height: "auto",
        width: 'auto',
        dialogClass: 'uploader',
        closeOnEscape: false, draggable: false, zIndex: "100", position: "left top"
        //                close: function(ev, ui) { $('#target').imgAreaSelect({remove: true});  $(this).close();  }
    }));


    $('#target').imgAreaSelect({
        x1: 0, y1: 0, x2: 0, y2: 0,
        aspectRatio: '1:1',
        handles: true,
        zIndex: 1000000,
        onInit: function (img, selection) {

            $("#x1").val(0);
            $("#y1").val(0);
            $("#x2").val(0);
            $("#y2").val(0);
            $("#w").val(0);
            $("#h").val(0);
        },
        onSelectEnd: function (img, selection) {

            $("#x1").val(selection.x1);
            $("#y1").val(selection.y1);
            $("#x2").val(selection.x2);
            $("#y2").val(selection.y2);
            $("#w").val(selection.width);
            $("#h").val(selection.height);

        }
    });
}

$(document).on('click','.deleted-image',function(e) {

    var imaageName =  $(this).attr('src').split('/');
    imaageName =  imaageName[imaageName.length-1];

    var mainImageCollback = function(e){

        var imaageName = $(e.currentTarget).attr('src');
        var val = $('input[name="image"]').val();
        var serchIndex = val.split(',').indexOf(imaageName);
        var arr =  val.split(',');
        if(arr.length==1){
            $('input[name="image"]').val('');
        }else{
            var buf =   arr.splice(serchIndex,1);
            $('input[name="image"]').val(arr.join(','));
        }

        if($('#main_image').val()!=''){
            if(arr.join(',')==''){
                $('input[name="image"]').val($('input[name="image"]').val($('#main_image').val()));
            }else{
                $('input[name="image"]').val($('#main_image').val()+','+arr.join(','));
            }
        }
        $('#main_image').val($(e.currentTarget).attr('src'));
        $('.main-image').removeClass('main-image');
        $(e.currentTarget).addClass('main-image');

    };

    var deleteCollback = function(e){

        var imaageName = $(e.currentTarget).attr('src');
        var val = $('input[name="image"]').val();
        var serchIndex = val.split(',').indexOf(imaageName);
        var arr =  val.split(',');

        if(arr.length==1){
            $('input[name="image"]').val('');
            arr='';
        }else{
            var buf =   arr.splice(serchIndex,1);
            $('input[name="image"]').val(arr.join(','));
        }

        $(e.currentTarget).remove();
        $('.prompt').dialog('close');
        $.post('/admin/deletedFiles',{src : imaageName,table:'Product',row : 'image',data:arr.join(','),id_product:$('#id_product').val()})
            .done(function(data) {
                $('.prompt').dialog('close');
            });

    };

    PopUpMain('Выберете действее', 'сообщение',e , deleteCollback,mainImageCollback);

});


$(document).on('click','.deleted-color',function(e) {

    var imaageName =  $(this).attr('src').split('/');
    imaageName =  imaageName[imaageName.length-1];

    var noCollback = function(e){
        $('.prompt').dialog('close');
    };

    var yesCollback = function(e){

        var imaageName = $(e.currentTarget).attr('src');
        var valImage = $('#image-color').val();
        var valColor = $('#input-color').val();
        var serchIndex = valImage.split(',').indexOf(imaageName);
        var colorName = valColor.split(',')[serchIndex];

        var arrImage =  valImage.split(',');
        var arrColor =  valColor.split(',');

        if(arrImage.length==1){
            $('#image-color').val('');
            $('#input-color').val('');

        }else{
            arrImage.splice(serchIndex,1);
            arrColor.splice(serchIndex,1);
            $('#image-color').val(arrImage.join(','));
            $('#input-color').val(arrColor.join(','));
        }

        $(e.currentTarget).remove();

        $.post('/admin/deletedFiles',{src :imaageName , table : 'Colors' , row:'image_color' , id_product:$('#id_product').val(),color:colorName})
            .done(function(data) {
                $('.prompt').dialog('close');
            });
    };

    PopUp('Удалить цвет', 'сообщение',e , yesCollback,noCollback);

});


$(document).on('click','.deleted-file',function(e) {

    var yesCollback = function(e){

        var imaageName =  $(e.currentTarget).find('.pdf-title').text();

        var val = $('input[name="file"]').val();

        var serchIndex = val.split(',').indexOf(imaageName);

        var arr =  val.split(',');
        if(arr.length==1){
            $('input[name="file"]').val('');
            arr=[];
        }else{
            var buf =   arr.splice(serchIndex,1);
            $('input[name="file"]').val(arr.join(','));
        }
        $(e.currentTarget).remove();
        $.post('/admin/deletedFiles',{src : imaageName,id_product:$('#id_product').val(),table:'Product',row:'file',data:arr.join(',')})
            .done(function(data) {
                $('.prompt').dialog('close');
            });

    };
    PopUp('вы хотите удалить этот фаил', 'сообщение',e , yesCollback);

});



</script>



