<?php
    $i=1;
    $formEdit->prepare();
    echo $this->form()->openTag($formEdit);
    foreach($categoryDataW as $key=>$value) {
        $i++;

?>
        <?php echo $this->formRow($formEdit->get('title_'.$i)); ?>
        <?php echo $this->formRow($formEdit->get('id_'.$i));   ?>


    <?php } ?>
<button name="edit">сохранить</button>

<br />
<?php

$formEdit->prepare();
echo $this->form()->openTag($formAdd);?>

<?php echo $this->formRow($formAdd->get('title')); ?>
<button name="add">сохранить</button>
<?php echo $this->form()->closeTag();?>
